### PR TITLE
feat(title): allow usage of $index in title

### PR DESCRIPTION
**Pull request by MathRobin**
refers to #64

### CODE REVIEW

**Comment by MathRobin** [comment]
Seems that you have a settings problem:

`No CODECLIMATE_REPO_TOKEN found. A CODECLIMATE_REPO_TOKEN must be specified as an environment variable.`

**Comment by lawrencec** [comment]
PR looks good. I appreciate it as I've not had time.

As to the Code Climate issue, looks like the codeclimate-test-reporter has been deprecated [1] and the way travis and code climate integrates has changed. If you remove the code-climate-reporter call in the `coverage` task in `package.json`, PR should be mergeable.

[1]

**Comment by lawrencec** [comment]
I've just merged a PR that switches to coveralls instead of code-climate (docs were not consistent). So if you rebase from master you won't need to make any further changes.

Thanks!

**Comment by MathRobin** [comment]
done!

**Comment by MathRobin** [comment]
Hi, no news ?

**Comment by MathRobin** [comment]
Many thanks^^

**Pull request merged**
